from .response_message import ResponseMessage
from .mscatalogo_service import ClienteCatalogoService
from .mscompras_service import ClienteComprasService
from .mspagos_service import ClientePagosService
from .msinventario_service import ClienteInventariosService
from .ecommerce_service import EcommerceService